### ISSUE TITLE
Application does not support 64bit architecture

### ISSUE THREAD

**Issue by sam1827** [clean-apps/CleanSCAN#25]
Can you provide us with the 64bit library as the scan module is not compatible with 64 bit architecture.

**Comment by babanomania** [comment]
@sam1827  thanks for  the tip, i'll start working to upgrade the codebase to OpenCV4.
The current library does not have X86_64 jni support.

One question though, how do you manage to find this ? i have a Snapdragon 855+ and the app works fine there

**Comment by babanomania** [comment]
Check the latest release 1.5.20200713, 64bit jni support added
