### ISSUE TITLE
Native Memory leak bug

### ISSUE THREAD

**Issue by maxakash** [clean-apps/CleanSCAN#29]
As soon as ScanActivity is opened, native memory leaks starts.

Staying  on ScanActivity , Native memory consumption keeps increasing util the app crashes.

I think the issue is related to usage of OpenCV.

Please let me know how to fix it.

**Comment by babanomania** [comment]
Can you help me in replicating the issue, did you managed to find this issue in a physical device ?

**Comment by maxakash** [comment]
I fixed it, it was the camera library that was leaking memory.
